### ISSUE TITLE
Does acl work?

### ISSUE THREAD

**Issue by peceka** [arioch/puppet-haproxy#7]
Hi,

tried to set custom acl but it seams it does not work. My hiera file:

```
'https_frontend':
  instance: 'frontend'
  bind: ':443 ssl crt /etc/haproxy/cert.pem ciphers AES256+EECDH:AES256+EDH no-sslv3'
  option:
    - 'httplog'
    - 'forwardfor'
    - 'http-server-close'
    - 'httpclose'
  acl:
    'acl_pool1':
      acl_header: 'example.org'
      acl_backend: pool1'
```

And module builds smth like this (haproxy.cfg):

```
frontend https_frontend
    mode            http
    bind            :443 ssl crt /etc/haproxy/cert.pem ciphers AES256+EECDH:AES256+EDH no-sslv3
    option          httplog
    option          forwardfor
    option          http-server-close
    option          httpclose
```

In templates/instance_frontend.erb there is nothing about acl variables.

It is known bug?

Regards,
p.
